# Generated by Django 5.2.6 on 2025-10-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('Temperatura', models.CharField(max_length=50)),
                ('Humedad', models.CharField(max_length=50)),
                ('PH', models.CharField(max_length=50)),
                ('Estado', models.IntegerField(max_length=1)),
            ],
        ),
    ]
