# Generated by Django 5.2.6 on 2025-11-08 02:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasificador', '0002_remove_miplanta_apodo_remove_miplanta_ubicacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='miplanta',
            unique_together={('usuario', 'especie')},
        ),
    ]
